### ISSUE TITLE
Git项目名称为什么是南瓜书而不是watermelon-book？

### ISSUE THREAD

**Issue by vnnw** [Datawhale18/pumpkin-book#7]
Git项目名称为什么是南瓜书而不是watermelon-book？

**Comment by Sm1les** [comment]
我们只是对西瓜书里的公式补充点推导和解析而已，担不起watermelon-book这个名字，pumpkin-book这种抖机灵的名字更适合我们

**Comment by Sm1les** [comment]
> Git项目名称为什么是南瓜书而不是watermelon-book？

我们只是对西瓜书里的公式补充点推导和解析而已，担不起watermelon-book这个名字，pumpkin-book这种抖机灵的名字更适合我们
